### ISSUE TITLE
Deploy was working, now fails with 'getaddrinfo ENOTFOUND' error

### ISSUE THREAD

**Issue by MarkMT** [jschniper/ember-cli-deploy-cloudfiles#4] opened 2016-03-02 21:20 UTC
I've been using ember-cli-deploy-cloudfiles successfully to date but today my deploy failed with the following message:

```
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND identity.api.rackspacecloud.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```
Any clues as to what has happened?

**Comment by jschniper** [comment] 2016-03-02 21:27
There were some changes introduced to upgrade the package to work with ember-cli-deploy 0.5.x so I wanted to make sure that you had upgraded before digging in and looking for the problem.

**Comment by MarkMT** [comment] 2016-03-02 21:43
I'm using ember-cli-deploy-cloudfiles version 0.1.0 and ember-cli-deploy version 0.6.0.

I set up a clean development environment about 2-3 weeks ago and probably did my last successful deployment on 2/22.

**Comment by jschniper** [comment] 2016-03-02 21:58
Okay, gotcha. Would you mind running `ember deploy` with the `--verbose` flag and providing the output?

**Comment by MarkMT** [comment] 2016-03-02 22:01
Sure thing:
```
$ ember deploy production --activate=true --verbose
version: 1.13.15
Registering hook -> configure[build]
Registering hook -> build[build]
Registering hook -> configure[cloudfiles]
Registering hook -> upload[cloudfiles]
Registering hook -> configure[redis]
Registering hook -> upload[redis]
Registering hook -> willActivate[redis]
Registering hook -> activate[redis]
Registering hook -> didDeploy[redis]
Registering hook -> configure[revision-data]
Registering hook -> prepare[revision-data]
Registering hook -> configure[ssh-tunnel]
Registering hook -> setup[ssh-tunnel]
Registering hook -> teardown[ssh-tunnel]
Executing pipeline
|
+- configure
|  |
|  +- build
|    - validating config
|    - Missing config: `outputPath`, using default: `tmp/deploy-dist`
|    - config ok
|  |
|  +- cloudfiles
|    - validating config
|    - Missing config: `enabled`, using default: `true`
|    - Missing config: `filePattern`, using default: `**/*.{js,css,png,gif,ico,jpg,map,xml,txt,svg,swf,eot,ttf,woff,woff2}`
|    - Missing config: `prefix`, using default: ``
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `distFiles`, using default: `[Function]`
|    - Missing config: `manifestPath`, using default: `[Function]`
|    - Missing config: `uploadClient`, using default: `[Function]`
|    - Missing config: `cloudFilesClient`, using default: `[Function]`
|    - config ok
|  |
|  +- redis
|    - validating config
|    - Missing config: `host`, using default: `localhost`
|    - Missing config: `port`, using default: `[Function]`
|    - Missing config: `filePattern`, using default: `index.html`
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `keyPrefix`, using default: `[Function]`
|    - Missing config: `activationSuffix`, using default: `current`
|    - Missing config: `activeContentSuffix`, using default: `current-content`
|    - Missing config: `revisionKey`, using default: `[Function]`
|    - Missing config: `didDeployMessage`, using default: `[Function]`
|    - Missing config: `redisDeployClient`, using default: `[Function]`
|    - Missing config: `maxRecentUploads`, using default: `10`
|    - config ok
|  |
|  +- revision-data
|    - validating config
|    - Missing config: `type`, using default: `file-hash`
|    - Missing config: `filePattern`, using default: `index.html`
|    - Missing config: `distDir`, using default: `[Function]`
|    - Missing config: `distFiles`, using default: `[Function]`
|    - Missing config: `versionFile`, using default: `package.json`
|    - config ok
|  |
|  +- ssh-tunnel
|    - validating config
|    - Missing config: `dstPort`, using default: `6379`
|    - Missing config: `dstHost`, using default: `localhost`
|    - Missing config: `srcPort`, using default: `[Function]`
|    - Missing config: `tunnelClient`, using default: `[Function]`
|    - config ok
|
+- setup
|  |
|  +- ssh-tunnel
|
+- willDeploy
|
+- willBuild
|
+- build
|  |
|  +- build
|    - building app to `tmp/deploy-dist` using buildEnv `production`...
|    - ✔  assets/crawsailing-ca2dbd3114a447a028577da4cbfe2be6.js
|    - ✔  assets/crawsailing-d41d8cd98f00b204e9800998ecf8427e.css
|    - ✔  assets/vendor-d41d8cd98f00b204e9800998ecf8427e.css
|    - ✔  assets/vendor-f6ef9a8993a13bbd8bda1c9c3c7469fc.js
|    - ✔  crossdomain.xml
|    - ✔  index.html
|    - ✔  robots.txt
|    - build ok
|
+- didBuild
|
+- willPrepare
|
+- prepare
|  |
|  +- revision-data
|    - creating revision data using `file-hash`
|    - generated revision data for revision: `c7bcb3d92412d9b11d711e1af5e632d2`
|
+- didPrepare
|
+- willUpload
|
+- upload
|  |
|  +- cloudfiles
|    - preparing to upload to CloudFiles container `static_assets`
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: getaddrinfo ENOTFOUND identity.api.rackspacecloud.com
    at errnoException (dns.js:44:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:94:26)
```

**Comment by MarkMT** [comment] 2016-03-02 22:07
Does this shed any light?? - http://stackoverflow.com/questions/17690803/node-js-getaddrinfo-enotfound

**Comment by jschniper** [comment] 2016-03-02 22:13
The error message looks pretty generic for just being unable to perform a hostname lookup. The actual URL seems to return as expected, plus all of that is actually handled by the pkgcloud library under the hood. I haven't tried it with ember-cli-deploy 0.6.x yet so I'll give that a shot and see if I can reproduce it.

Just for sanity's sake, you get a successful response from https://identity.api.rackspacecloud.com? It should return some XML.

**Comment by MarkMT** [comment] 2016-03-02 22:16
Thanks. Yes I get the XML response from https://identity.api.rackspacecloud.com.

**Comment by MarkMT** [comment] 2016-03-02 22:47
Actually a point of clarification... The development environment that I have been using successfully over the last few weeks is based on ember-cli-deploy v0.5.1 and this produced the error message that I reported above. However I first discovered the issue when I set up another development environment today for another project. Installing ember-cli-install for that project resulted 0.6.0 being installed and this produced exactly the same error message when I attempted to deploy. It was when I ran into this that I went back to the previous project to check that I could deploy that ok and discovered that it also was no longer working.

**Comment by jschniper** [comment] 2016-03-02 22:51
So I upgraded to 0.6.0 and I'm unable to reproduce the error. Is there anything else about the environment that could be preventing the hostname lookup?

Are you on a *nix machine by the way?

**Comment by MarkMT** [comment] 2016-03-02 22:54
Yes my development machine is Linux Mint 17.

I'll have to have a think about what else might have changed.

**Comment by jschniper** [comment] 2016-03-02 23:02
It might be worth a shot to change your DNS resolvers to point towards Google's DNS servers (8.8.8.8 or 8.8.4.4) and see if anything changes. I'm honestly stumped by this one.

**Comment by MarkMT** [comment] 2016-03-02 23:38
Well changing the DNS settings as you suggested actually fixed it. So thanks! I'm not sure I understand why it stopped resolving with the default setting, but at least I press on now.

**Comment by jschniper** [comment] 2016-03-03 15:45
Glad to hear that you got past it.

I'm curious as to why it stopped resolving as well. That's definitely a new one.

**Closed** 2016-04-26 20:26 UTC
